Always set default price on customer to 70%. Every time a parent company with sub companies is created, the group pricing for the parent company is applied to all the sub companies. Every time a new customer is created, the default group pricings should be set to specified settings (from a custom record)
finitydevs/dpc-default-price-customer pull request #1
Opened 2022-01-06 14:35 UTC by eliyahumoskowitz

Every time a parent company with sub companies is created, the group pricing for the parent company is applied to all the sub companies.
Every time a new customer is created, the default group pricings should be set to specified settings (from a custom record)

2022-01-06 22:04 UTC, azigoldstein commented
![image](https://user-images.githubusercontent.com/33836715/148458485-38f157e7-0c95-4ab2-a3aa-6f022dcf5128.png)

![image](https://user-images.githubusercontent.com/33836715/148458577-f02d5389-5571-4956-a939-fa96d3032bef.png)

The ticket says that the independent checkbox should be in the pricing subtab. Maybe this wasn't  clear but I meant the subtab where all the pricing information shows up. I.e. the `financial` subtab

2022-01-06 22:07 UTC, azigoldstein commented
If a change is made to the parent, it is only overriding the group pricings that were on the child before.
However it a group pricing is added to the parent it is not adding it to the child.

2022-01-06 22:12 UTC, azigoldstein commented
Creating a new child customer only got the first pricing group from the parent and not all

2022-01-06 22:19 UTC, eliyahumoskowitz commented
Which one should it get?
That was a Q I had, so I just took the first

On Thu, Jan 6, 2022, 5:13 PM azigoldstein ***@***.***> wrote:

> Creating a new child customer only got the first pricing group from the
> parent and not all
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/finitydevs/dpc-default-price-customer/pull/1#issuecomment-1006972837>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APT3PWCHUK65GMZT3FSS52TUUYHXLANCNFSM5LMO3K3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-06 22:22 UTC, eliyahumoskowitz commented
It automatically puts it by custom subtab

On Thu, Jan 6, 2022, 5:04 PM azigoldstein ***@***.***> wrote:

> [image: image]
> <https://user-images.githubusercontent.com/33836715/148458485-38f157e7-0c95-4ab2-a3aa-6f022dcf5128.png>
>
> [image: image]
> <https://user-images.githubusercontent.com/33836715/148458577-f02d5389-5571-4956-a939-fa96d3032bef.png>
>
> The ticket says that the independent checkbox should be in the pricing
> subtab. Maybe this wasn't clear but I meant the subtab where all the
> pricing information shows up. I.e. the financial subtab
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/finitydevs/dpc-default-price-customer/pull/1#issuecomment-1006967926>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APT3PWCELA4P7ZAQXI6ROE3UUYGX7ANCNFSM5LMO3K3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-06 23:04 UTC, azigoldstein commented
> It automatically puts it by custom subtab
You can choose where it goes

2022-01-06 23:05 UTC, azigoldstein commented
> Which one should it get?
That was a Q I had, so I just took the first

Why would it just get the first? If you have a Q, instead of just grabbing one, I suggest you ask the Q

2022-01-07 02:02 UTC, eliyahumoskowitz commented
Ok so which one?
Actually in my code,  there us a comment:
"Harcode one???"

On Thu, Jan 6, 2022, 6:05 PM azigoldstein ***@***.***> wrote:

> Which one should it get?
> That was a Q I had, so I just took the first
>
> Why would it just get the first? If you have a Q, instead of just grabbing
> one, I suggest you ask the Q
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/finitydevs/dpc-default-price-customer/pull/1#issuecomment-1006999827>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APT3PWGXAEDY3JQLHC3WBGTUUYN3NANCNFSM5LMO3K3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-07 02:03 UTC, eliyahumoskowitz commented
I didn't see that option

On Thu, Jan 6, 2022, 6:04 PM azigoldstein ***@***.***> wrote:

> It automatically puts it by custom subtab
>
> You can choose where it goes
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/finitydevs/dpc-default-price-customer/pull/1#issuecomment-1006999271>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APT3PWC2E7CEUCYQO2CLUBTUUYNWZANCNFSM5LMO3K3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-01-07 15:11 UTC, azigoldstein commented
> Ok so which one?
Actually in my code,  there us a comment:
"Harcode one???"

I didn't look at code yet. The first thing I did was see if it works as expected

2022-01-07 18:43 UTC, azigoldstein requested changes
There may be more comments but for now these are my comments.
Also the folder structure is not matching convention.
We don't have subfolders labeld `scripts on x record`
It is like this
`project name_scripttypeabrreviation_recordtype_nameforfile`


You can break up the folder into script types if you want
`UserEventScripts`
`ClientScripts`
`Utilities`
But what the script is running on should not be a folder name nor is it true and you suitelet is not a script on a customer.

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_mr_dpc_default_price_customer.ts
> +        const parentId = searchResult.values?.["parentCustomer.internalid"]?.[0]?.value // maybe get parentId from param?
Eliyahu, I have said this many times.  Ehen you use the question mark syntax all over I assume you are saying there is a possibility that it will be undefined. If that's the case you have to deal with it like it might be undefined. You can't do a record load on line 50 with a value that might be undefined here

I feel like this question mark syntax could cause more problems then it helps if its not dealt with properly

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +// type ExecuteSublstArrayMapParams = {
What's with the commented out code?

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +            if (parentId && (!isIndependent || isIndependent == 'F')) {
What's with both `!isIndependent || isIndependent == 'F')`?

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +            const defaultPriceLevelId = String(runtime.getCurrentScript().getParameter({ name: 'custscriptdefault_price_level_customer' }))
Was the script parameter set up wrong?
There should be an underscore between `custscript` and `default`

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +                newRecord.setValue({ fieldId: 'pricelevel', value: defaultPriceLevelId })
This is definitely not correct. 
This says that anything that is not create will set the default price level id to the parameter.
That means any customer that's edited after the parameter value is changed is going to be updated.
This is meant to be a default not an updater

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +                const theParent = record.load({ type: record.Type.CUSTOMER, id: parentId })
Does this need to be a record load and not a search and query.
Record load is the slowest way to do things, so usually we only do if there is a good reason

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +        if (type == UserEventType.EDIT) {       // edit mode on parent - trigger mr on subs
Comment says `edit mode on parent` but I am not sure what would restrict this to parent

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +            const oldParentSublist = Array.from(Array(oldParentSublistLineCount).keys()).reduce((pre, cur) => {
I think its time to use ramda `R.range` These Array.from(Array ) are getting very hard to read

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_su_dpc_get_pricelevel.ts
> +    console.log('🚀 ~ file: fd_dpc_su_get_pricelevel.ts ~ line 17 ~ priceGroupId', priceGroupId)
Console?

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_su_dpc_get_pricelevel.ts
> +
Console?

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_su_dpc_get_pricelevel.ts
> +        response.write(JSON.stringify(theNewPriceLevel || 'There is no Default Group Pricing record level for this group'))
So you want to return the price level or a string and then check if it becomes NaN on the other side? This is very untyped and should be fixed.

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_mr_dpc_default_price_customer.ts
> +        const parent = record.load({ type: record.Type.CUSTOMER, id: parentId })
We are doing a lot of record loading. Is this all needed? Can it not be a query or a search?
If not lets at least make it a utility function so that we don't have repeated code like this

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_mr_dpc_default_price_customer.ts
> +        if (!isIndependent || isIndependent == 'F') {
What with this? Which is the proper one to do? 
`!isIndependent || isIndependent == 'F'`

If you don't know, test it and use the proper one

2022-01-07 18:43 UTC, azigoldstein commented on scripts_on_customer/fd_mr_dpc_default_price_customer.ts
> +                if ((customerSublist[group] || customerSublist[group] == 0) && (oldParentSublist[group] != customerSublist[group])) return
`customerSublist[group] || customerSublist[group] == 0)` 
What are you attempting to do with this?

2022-01-10 17:00 UTC, eliyahumoskowitz commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +            if (parentId && (!isIndependent || isIndependent == 'F')) {
im not 100% sure what it will be

2022-01-10 17:00 UTC, eliyahumoskowitz commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +            if (parentId && (!isIndependent || isIndependent == 'F')) {
it might be undefined

2022-01-10 17:16 UTC, eliyahumoskowitz commented on scripts_on_customer/fd_ue_dpc_default_price_customer.ts
> +                const theParent = record.load({ type: record.Type.CUSTOMER, id: parentId })
yes cuz we need sublist value

2022-01-10 21:04 UTC, azigoldstein reviewed
There is more to review, but I am burned out of PR so fix these for now please

2022-01-11 17:45 UTC, closed without merging